# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/m86/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/app/mcRegistry/04010000000000000000000000000000.tlbin:system/app/mcRegistry/04010000000000000000000000000000.tlbin \
    vendor/meizu/m86/proprietary/app/mcRegistry/04020000000000000000000000000000.tlbin:system/app/mcRegistry/04020000000000000000000000000000.tlbin \
    vendor/meizu/m86/proprietary/app/mcRegistry/07020000000000000000000000000000.tlbin:system/app/mcRegistry/07020000000000000000000000000000.tlbin \
    vendor/meizu/m86/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/meizu/m86/proprietary/app/mcRegistry/07061000000000000000000000000000.tlbin:system/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/meizu/m86/proprietary/bin/86_OTP.sh:system/bin/86_OTP.sh \
    vendor/meizu/m86/proprietary/bin/check_OTP.sh:system/bin/check_OTP.sh \
    vendor/meizu/m86/proprietary/bin/modem_switch.sh:system/bin/modem_switch.sh \

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg.bin \
    vendor/meizu/m86/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg_w_hdrs.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg_w_hdrs.bin \
    vendor/meizu/m86/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_training_bkg.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_training_bkg.bin \
    vendor/meizu/m86/proprietary/etc/firmware/audience/cvqmodels/oemkw_NihaoMeizu.bin:system/etc/firmware/audience/cvqmodels/oemkw_NihaoMeizu.bin \
    vendor/meizu/m86/proprietary/etc/firmware/audience/es705/audience-es705-fw.bin:system/etc/firmware/audience/es705/audience-es705-fw.bin \
    vendor/meizu/m86/proprietary/etc/firmware/audience/es705/audience-es705-vs.bin:system/etc/firmware/audience/es705/audience-es705-vs.bin \
    vendor/meizu/m86/proprietary/etc/firmware/stage1.txt:system/etc/firmware/stage1.txt \
    vendor/meizu/m86/proprietary/etc/firmware/stage2.txt:system/etc/firmware/stage2.txt \
    vendor/meizu/m86/proprietary/etc/tfa98xx/MZ_M86_speaker.speaker:system/etc/tfa98xx/MZ_M86_speaker.speaker \
    vendor/meizu/m86/proprietary/etc/tfa98xx/TFA9890_N1B12_N1C3_v3.config:system/etc/tfa98xx/TFA9890_N1B12_N1C3_v3.config \
    vendor/meizu/m86/proprietary/etc/tfa98xx/TFA9890_N1C3_2_1_1.patch:system/etc/tfa98xx/TFA9890_N1C3_2_1_1.patch \
    vendor/meizu/m86/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/meizu/m86/proprietary/etc/tfa98xx/music_eq_0.eq:system/etc/tfa98xx/music_eq_0.eq \
    vendor/meizu/m86/proprietary/etc/tfa98xx/music_preset_0.preset:system/etc/tfa98xx/music_preset_0.preset \
    vendor/meizu/m86/proprietary/etc/tfa98xx/speech_eq_0.eq:system/etc/tfa98xx/speech_eq_0.eq \
    vendor/meizu/m86/proprietary/etc/tfa98xx/speech_preset_0.preset:system/etc/tfa98xx/speech_preset_0.preset \
    vendor/meizu/m86/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/vendor/etc/dirac_types.xml:system/vendor/etc/dirac_types.xml \
    vendor/meizu/m86/proprietary/vendor/etc/diracmobile.config:system/vendor/etc/diracmobile.config \
    vendor/meizu/m86/proprietary/vendor/firmware/Project.hex:system/vendor/firmware/Project.hex \
    vendor/meizu/m86/proprietary/vendor/firmware/bcm43455.hcd:system/vendor/firmware/bcm43455.hcd \
    vendor/meizu/m86/proprietary/vendor/firmware/bcm4349.hcd:system/vendor/firmware/bcm4349.hcd \
    vendor/meizu/m86/proprietary/vendor/firmware/bcm943455_pciehdr_follow_M8.bin:system/vendor/firmware/bcm943455_pciehdr_follow_M8.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/fw_bcmdhd.bin:system/vendor/firmware/fw_bcmdhd.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/fw_bcmdhd_apsta.bin:system/vendor/firmware/fw_bcmdhd_apsta.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/meizu/m86/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/mfg_fw.bin:system/vendor/firmware/mfg_fw.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/modem.bin:system/vendor/firmware/modem.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/setfile_2p2.bin:system/vendor/firmware/setfile_2p2.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/setfile_imx230.bin:system/vendor/firmware/setfile_imx230.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/setfile_ov5670.bin:system/vendor/firmware/setfile_ov5670.bin \
    vendor/meizu/m86/proprietary/vendor/firmware/st_fts.bin:system/vendor/firmware/st_fts.bin \

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/bin/cbd:system/bin/cbd \
    vendor/meizu/m86/proprietary/bin/dis_effect:system/bin/dis_effect \
    vendor/meizu/m86/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/meizu/m86/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/meizu/m86/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/meizu/m86/proprietary/bin/march_hotplug:system/bin/march_hotplug \
    vendor/meizu/m86/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/meizu/m86/proprietary/bin/radiooptions_exynos:system/bin/radiooptions_exynos \
    vendor/meizu/m86/proprietary/bin/record_panic_msg:system/bin/record_panic_msg \
    vendor/meizu/m86/proprietary/bin/rild_exynos:system/bin/rild_exynos \
    vendor/meizu/m86/proprietary/bin/wl:system/bin/wl \

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.adpcmdec.so:system/lib/extend/libCodec.adpcmdec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.adt.so:system/lib/extend/libCodec.adt.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.alacdec.so:system/lib/extend/libCodec.alacdec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.ape.so:system/lib/extend/libCodec.ape.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.dsddec.so:system/lib/extend/libCodec.dsddec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.dts.so:system/lib/extend/libCodec.dts.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.lpcm.so:system/lib/extend/libCodec.lpcm.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.mp3dec.so:system/lib/extend/libCodec.mp3dec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.mp3enc.so:system/lib/extend/libCodec.mp3enc.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.mpegdec.so:system/lib/extend/libCodec.mpegdec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.radec.so:system/lib/extend/libCodec.radec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.raw.so:system/lib/extend/libCodec.raw.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.rvdec.so:system/lib/extend/libCodec.rvdec.so \
    vendor/meizu/m86/proprietary/lib/extend/libCodec.wmadec.so:system/lib/extend/libCodec.wmadec.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.AC3.so:system/lib/extend/libExtractor.AC3.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.AIFF.so:system/lib/extend/libExtractor.AIFF.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.APE.so:system/lib/extend/libExtractor.APE.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.ASF.so:system/lib/extend/libExtractor.ASF.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.AVI.so:system/lib/extend/libExtractor.AVI.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.DTS.so:system/lib/extend/libExtractor.DTS.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.FLAC.so:system/lib/extend/libExtractor.FLAC.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.FLV.so:system/lib/extend/libExtractor.FLV.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.MP3.so:system/lib/extend/libExtractor.MP3.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.MPEG.so:system/lib/extend/libExtractor.MPEG.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.MPEG2TS.so:system/lib/extend/libExtractor.MPEG2TS.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.MPEG4.so:system/lib/extend/libExtractor.MPEG4.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.REALMEDIA.so:system/lib/extend/libExtractor.REALMEDIA.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.WAV.so:system/lib/extend/libExtractor.WAV.so \
    vendor/meizu/m86/proprietary/lib/extend/libExtractor.matroska.so:system/lib/extend/libExtractor.matroska.so \
    vendor/meizu/m86/proprietary/lib/hw/audio.primary.m86.so:system/lib/hw/audio.primary.m86.so \
    vendor/meizu/m86/proprietary/lib/hw/camera.m86.so:system/lib/hw/camera.m86.so \
    vendor/meizu/m86/proprietary/lib/hw/dis_effect.m86.so:system/lib/hw/dis_effect.m86.so \
    vendor/meizu/m86/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/meizu/m86/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/meizu/m86/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/meizu/m86/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/meizu/m86/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/meizu/m86/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/meizu/m86/proprietary/lib/libSonyIMX230PdafLibrary.so:system/lib/libSonyIMX230PdafLibrary.so \
    vendor/meizu/m86/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/meizu/m86/proprietary/lib/libdisplaymodule.so:system/lib/libdisplaymodule.so \
    vendor/meizu/m86/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/meizu/m86/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/meizu/m86/proprietary/lib/libhwcutilsmodule.so:system/lib/libhwcutilsmodule.so \
    vendor/meizu/m86/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/meizu/m86/proprietary/lib/libimageproc.so:system/lib/libimageproc.so \
    vendor/meizu/m86/proprietary/lib/libmeizucamera.so:system/lib/libmeizucamera.so \
    vendor/meizu/m86/proprietary/lib/libril_sitril.so:system/lib/libril_sitril.so \
    vendor/meizu/m86/proprietary/lib/librilutils_sitril.so:system/lib/librilutils_sitril.so \
    vendor/meizu/m86/proprietary/lib/libsfb.so:system/lib/libsfb.so \
    vendor/meizu/m86/proprietary/lib/libsitril-audio.so:system/lib/libsitril-audio.so \
    vendor/meizu/m86/proprietary/lib/libsitril-client.so:system/lib/libsitril-client.so \
    vendor/meizu/m86/proprietary/lib/libsitril-gps.so:system/lib/libsitril-gps.so \
    vendor/meizu/m86/proprietary/lib/libsitril-ims.so:system/lib/libsitril-ims.so \
    vendor/meizu/m86/proprietary/lib/libsitril-jniif.so:system/lib/libsitril-jniif.so \
    vendor/meizu/m86/proprietary/lib/libsitril-wlan.so:system/lib/libsitril-wlan.so \
    vendor/meizu/m86/proprietary/lib/libsitril.so:system/lib/libsitril.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/meizu/m86/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/meizu/m86/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/meizu/m86/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/meizu/m86/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/meizu/m86/proprietary/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
    vendor/meizu/m86/proprietary/lib64/extend/libCodec.adpcmdec.so:system/lib64/extend/libCodec.adpcmdec.so \
    vendor/meizu/m86/proprietary/lib64/extend/libCodec.adt.so:system/lib64/extend/libCodec.adt.so \
    vendor/meizu/m86/proprietary/lib64/extend/libCodec.lpcm.so:system/lib64/extend/libCodec.lpcm.so \
    vendor/meizu/m86/proprietary/lib64/extend/libCodec.mp3enc.so:system/lib64/extend/libCodec.mp3enc.so \
    vendor/meizu/m86/proprietary/lib64/extend/libCodec.raw.so:system/lib64/extend/libCodec.raw.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.AC3.so:system/lib64/extend/libExtractor.AC3.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.AIFF.so:system/lib64/extend/libExtractor.AIFF.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.APE.so:system/lib64/extend/libExtractor.APE.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.ASF.so:system/lib64/extend/libExtractor.ASF.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.AVI.so:system/lib64/extend/libExtractor.AVI.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.FLAC.so:system/lib64/extend/libExtractor.FLAC.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.FLV.so:system/lib64/extend/libExtractor.FLV.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.MP3.so:system/lib64/extend/libExtractor.MP3.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.MPEG.so:system/lib64/extend/libExtractor.MPEG.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.MPEG2TS.so:system/lib64/extend/libExtractor.MPEG2TS.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.MPEG4.so:system/lib64/extend/libExtractor.MPEG4.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.REALMEDIA.so:system/lib64/extend/libExtractor.REALMEDIA.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.WAV.so:system/lib64/extend/libExtractor.WAV.so \
    vendor/meizu/m86/proprietary/lib64/extend/libExtractor.matroska.so:system/lib64/extend/libExtractor.matroska.so \
    vendor/meizu/m86/proprietary/lib64/hw/audio.primary.m86.so:system/lib64/hw/audio.primary.m86.so \
    vendor/meizu/m86/proprietary/lib64/hw/dis_effect.m86.so:system/lib64/hw/dis_effect.m86.so \
    vendor/meizu/m86/proprietary/lib64/hw/gps.default.so:system/lib64/hw/gps.default.so \
    vendor/meizu/m86/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
    vendor/meizu/m86/proprietary/lib64/hw/hwcomposer.exynos5.so:system/lib64/hw/hwcomposer.exynos5.so \
    vendor/meizu/m86/proprietary/lib64/hw/sensors.m86.so:system/lib64/hw/sensors.m86.so \
    vendor/meizu/m86/proprietary/lib64/libExynosOMX_Core.so:system/lib64/libExynosOMX_Core.so \
    vendor/meizu/m86/proprietary/lib64/libExynosOMX_Resourcemanager.so:system/lib64/libExynosOMX_Resourcemanager.so \
    vendor/meizu/m86/proprietary/lib64/libMcClient.so:system/lib64/libMcClient.so \
    vendor/meizu/m86/proprietary/lib64/libMcRegistry.so:system/lib64/libMcRegistry.so \
    vendor/meizu/m86/proprietary/lib64/libdisplay.so:system/lib64/libdisplay.so \
    vendor/meizu/m86/proprietary/lib64/libdisplaymodule.so:system/lib64/libdisplaymodule.so \
    vendor/meizu/m86/proprietary/lib64/libgps_shim.so:system/lib64/libgps_shim.so \
    vendor/meizu/m86/proprietary/lib64/libhwcutils.so:system/lib64/libhwcutils.so \
    vendor/meizu/m86/proprietary/lib64/libhwcutilsmodule.so:system/lib64/libhwcutilsmodule.so \
    vendor/meizu/m86/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
    vendor/meizu/m86/proprietary/lib64/libimageproc.so:system/lib64/libimageproc.so \
    vendor/meizu/m86/proprietary/lib64/libmeizucamera.so:system/lib64/libmeizucamera.so \
    vendor/meizu/m86/proprietary/lib64/libril_sitril.so:system/lib64/libril_sitril.so \
    vendor/meizu/m86/proprietary/lib64/librilutils_sitril.so:system/lib64/librilutils_sitril.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-audio.so:system/lib64/libsitril-audio.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-client.so:system/lib64/libsitril-client.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-gps.so:system/lib64/libsitril-gps.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-ims.so:system/lib64/libsitril-ims.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-jniif.so:system/lib64/libsitril-jniif.so \
    vendor/meizu/m86/proprietary/lib64/libsitril-wlan.so:system/lib64/libsitril-wlan.so \
    vendor/meizu/m86/proprietary/lib64/libsitril.so:system/lib64/libsitril.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:system/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.VP8.Decoder.so:system/lib64/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.VP8.Encoder.so:system/lib64/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/omx/libOMX.Exynos.WMV.Decoder.so:system/lib64/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/meizu/m86/proprietary/lib64/soundfx/libbundlewrapper.so:system/lib64/soundfx/libbundlewrapper.so \
    vendor/meizu/m86/proprietary/lib64/soundfx/libdownmix.so:system/lib64/soundfx/libdownmix.so \
    vendor/meizu/m86/proprietary/lib64/soundfx/libldnhncr.so:system/lib64/soundfx/libldnhncr.so \

PRODUCT_COPY_FILES += \
    vendor/meizu/m86/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/meizu/m86/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/meizu/m86/proprietary/vendor/lib/libexynosuvs.so:system/vendor/lib/libexynosuvs.so \
    vendor/meizu/m86/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/meizu/m86/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
    vendor/meizu/m86/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so

# 改由源码编译
PRODUCT_PACKAGES += \
    libion \
    libexynosutils \
    libexynosv4l2 \
    libion_exynos \
    libexynosscaler \
    libexynosgscaler \
    libmpp \
    libcsc \
    libstagefrighthw \
    memtrack.exynos5 \
    libtfa9890 \
    climax_tfa9890 \
    libExynosHWCService \
    libhdmimodule \
    libhdmi \
    libvirtualdisplay \
    libvirtualdisplaymodule \

